### ISSUE TITLE
VQGAN pretrained model

### ISSUE THREAD

**Issue by kairess** [KR-HappyFace/KoDALLE#15]
안녕하세요 훌륭한 프로젝트 잘 보고 배우고 있습니다. VQGAN 모델 다운로드 경로 알려주실수 있을까요?

wte, wpe 파일도 어디서 받는지 알려주시면 감사하겠습니다!

**Comment by snoop2head** [comment]
### Training VQGAN
VQGAN 모델은 V100 32GB x 1 기준으로 [train_vae.py](./vqgan/train_vae.py)을 일주일 동안 실행시키셔야 합니다.  

@kairess 님이 사용 목적만 알려주신다면, Pretrained VQGAN 모델 파일을 공유해드리겠습니다!

### Extracting Pretrained Token Embeddings and Position Embeddings
WTE, WPE파일은 다음과 같이 추출하셔서 저장하시면 됩니다.
```python
from transformers import AutoModel
import torch

MODEL_NAME='klue/roberta-large'
model=AutoModel.from_pretrained(MODEL_NAME) #load model

#extract model
wte=model.embeddings.word_embeddings
wpe=model.embeddings.position_embeddings
torch.save(wte,f'./{MODEL_NAME}_wte.pt')
torch.save(wpe,f'./{MODEL_NAME}_wpe.pt')
```

**Comment by kairess** [comment]
감사합니다 제가 빵형의 개발도상국이라는 유튜브 채널을 운영중인데 컨텐츠로 이 프로젝트를 소개하고자 합니다 혹시 메일로 모델 공유가능할까요?
kairess87@gmail.com

**Comment by snoop2head** [comment]
아 예전에 @kairess 님 확진자수 예측하는 프로젝트에 데이터셋 관련 PR 날렸던 것 같은데,,,
다시 뵙네요! 반갑습니다 ㅎㅎ

팀원들에게 동의만 구하고 다음 파일들 찾아서 보내드리겠습니다
다만 파이프라인 정리하고 모델 확인하는 등 시간은 좀 걸릴 것 같습니다
- Inference Pipeline ipynb 노트북
- VQGAN Pretrained Model
- DALLE Pretrained Model

영상에서 출처만 잘 밝혀주시고 관련해서 서포트 필요하신 거 있으면 young_ahn@yonsei.ac.kr로 연락주세요 ㅎㅎ

**Comment by kairess** [comment]
@snoop2head 영상에서 출처 밝히고 사용하도록 하겠습니다!

커스텀 데이터셋으로 train_vae.py 를 학습중인데요. 코드를 자세히보니 DiscreteVAE 를 베이스라인 모델로 사용하는 것 같은데
dVAE와 VQGAN이 동일한 아키텍쳐인가요?

현재 7에폭 학습중인데 뭔가 생각보다 퀄리티가 좋지 않아서 걱정이되네요 ㅎㅎ;
https://wandb.ai/kairess/DALLE-Couture?workspace=user-kairess

**Comment by snoop2head** [comment]
@kairess 
예전 프로젝트라서 소스 찾는데 시간이 좀 걸렸습니다...! 

### VQGAN vs DiscreteVAE
- 저희가 실험해본 결과 Reconstruction 성능으로만 따지면 DiscreteVAE < VQVAE < VQGAN입니다.
- VAE와 VQGAN은 아키텍쳐가 Encoder-Decoder 형식으로 동일하지만 차이점이 다음과 같이 있습니다. 
    - VQGAN은 Codebook에서 image patch를 가져온 다음 Autoregressive하게 채워나갑니다
    - VQGAN은 Decoder 뒤에 CNN Discriminator가 추가적으로 있어서 Local한 특징을 보다 현실적으로 구현해냅니다
- [VQGAN의 자세한 리뷰는 저희 팀원 jjonhwa 님의 리뷰](https://jjonhwa.github.io/booststudy/2021/12/24/booststudy-paper-VQGAN/)를 읽어보셔도 좋을 것 같습니다. @jjonhwa 

### How to train VQGAN
- 저희는 [taming-transformers의 repo를 fork해서 해당 명령어](https://github.com/KR-HappyFace/taming-transformers/blob/master/train.sh)로 훈련을 시켰습니다.
- VQGAN은 앞서 언급한 두 가지 특징으로 인해서 high resolution 이미지를 생성합니다. 
- [카카오브레인의 MinDALLE](https://github.com/kakaobrain/minDALL-E)도 저희처럼 VAE 대신에 VQGAN을 이미지 Generator로 사용했으며, 이 방식이 높은 화질의 이미지를 생성하는데 효과적이라는 언급도 있습니다.
`Unlike the original DALL-E [1], we replace Discrete VAE with VQGAN [2] to generate high-quality samples effectively.`

### VQGAN Weight 파일
- 원래는 epoch 7까지 돌린 파일이 있었는데, epoch 5까지 돌린 파일만 찾았습니다. 이메일로 보내드렸습니다
- DALLE를 훈련시킬 때는 Initialized Transformers Layer 16개(or less)에다가 미리 훈련된 VQGAN과 WPE & WTE을 연결시켜서 학습을 시켜야 합니다.

**Comment by snoop2head** [comment]
@kairess 님께 모델 전달해드렸고, 혹시나 원하시는 분이 더 계시다면 이슈를 여시거나 해당 이메일로 연락주시면 됩니다!
snoop2head@gmail.com
